# Generated by Django 4.2.6 on 2023-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('contrasenha', models.CharField(max_length=100, verbose_name='Contrasenha')),
            ],
        ),
    ]
